// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.0
// source: payment.proto

package paymentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED PaymentMethod = 0
	PaymentMethod_PAYMENT_METHOD_COD         PaymentMethod = 1
	PaymentMethod_PAYMENT_METHOD_ONLINE      PaymentMethod = 2
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "PAYMENT_METHOD_COD",
		2: "PAYMENT_METHOD_ONLINE",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED": 0,
		"PAYMENT_METHOD_COD":         1,
		"PAYMENT_METHOD_ONLINE":      2,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_payment_proto_enumTypes[0]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

type PaymentProvider int32

const (
	PaymentProvider_PAYMENT_PROVIDER_UNSPECIFIED PaymentProvider = 0
	PaymentProvider_PAYMENT_PROVIDER_STRIPE      PaymentProvider = 1
	PaymentProvider_PAYMENT_PROVIDER_SSLCOMMERZ  PaymentProvider = 2
	PaymentProvider_PAYMENT_PROVIDER_PAYPAL      PaymentProvider = 3
)

// Enum value maps for PaymentProvider.
var (
	PaymentProvider_name = map[int32]string{
		0: "PAYMENT_PROVIDER_UNSPECIFIED",
		1: "PAYMENT_PROVIDER_STRIPE",
		2: "PAYMENT_PROVIDER_SSLCOMMERZ",
		3: "PAYMENT_PROVIDER_PAYPAL",
	}
	PaymentProvider_value = map[string]int32{
		"PAYMENT_PROVIDER_UNSPECIFIED": 0,
		"PAYMENT_PROVIDER_STRIPE":      1,
		"PAYMENT_PROVIDER_SSLCOMMERZ":  2,
		"PAYMENT_PROVIDER_PAYPAL":      3,
	}
)

func (x PaymentProvider) Enum() *PaymentProvider {
	p := new(PaymentProvider)
	*p = x
	return p
}

func (x PaymentProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_proto_enumTypes[1].Descriptor()
}

func (PaymentProvider) Type() protoreflect.EnumType {
	return &file_payment_proto_enumTypes[1]
}

func (x PaymentProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentProvider.Descriptor instead.
func (PaymentProvider) EnumDescriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_COMPLETED   PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_REFUNDED    PaymentStatus = 4
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_COMPLETED",
		3: "PAYMENT_STATUS_FAILED",
		4: "PAYMENT_STATUS_REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_COMPLETED":   2,
		"PAYMENT_STATUS_FAILED":      3,
		"PAYMENT_STATUS_REFUNDED":    4,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_proto_enumTypes[2].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_payment_proto_enumTypes[2]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Method        PaymentMethod          `protobuf:"varint,4,opt,name=method,proto3,enum=payment.PaymentMethod" json:"method,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=payment.PaymentStatus" json:"status,omitempty"`
	Amount        int64                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Types that are valid to be assigned to Details:
	//
	//	*Payment_OnlineTransaction
	//	*Payment_CodDetail
	Details       isPayment_Details `protobuf_oneof:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Payment) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Payment) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Payment) GetMethod() PaymentMethod {
	if x != nil {
		return x.Method
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *Payment) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *Payment) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Payment) GetDetails() isPayment_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Payment) GetOnlineTransaction() *OnlineTransaction {
	if x != nil {
		if x, ok := x.Details.(*Payment_OnlineTransaction); ok {
			return x.OnlineTransaction
		}
	}
	return nil
}

func (x *Payment) GetCodDetail() *CODDetail {
	if x != nil {
		if x, ok := x.Details.(*Payment_CodDetail); ok {
			return x.CodDetail
		}
	}
	return nil
}

type isPayment_Details interface {
	isPayment_Details()
}

type Payment_OnlineTransaction struct {
	OnlineTransaction *OnlineTransaction `protobuf:"bytes,9,opt,name=online_transaction,json=onlineTransaction,proto3,oneof"`
}

type Payment_CodDetail struct {
	CodDetail *CODDetail `protobuf:"bytes,10,opt,name=cod_detail,json=codDetail,proto3,oneof"`
}

func (*Payment_OnlineTransaction) isPayment_Details() {}

func (*Payment_CodDetail) isPayment_Details() {}

type OnlineTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentId     int64                  `protobuf:"varint,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Provider      PaymentProvider        `protobuf:"varint,3,opt,name=provider,proto3,enum=payment.PaymentProvider" json:"provider,omitempty"`
	GatewayRef    string                 `protobuf:"bytes,4,opt,name=gateway_ref,json=gatewayRef,proto3" json:"gateway_ref,omitempty"`
	GatewayStatus string                 `protobuf:"bytes,5,opt,name=gateway_status,json=gatewayStatus,proto3" json:"gateway_status,omitempty"`
	RawResponse   string                 `protobuf:"bytes,6,opt,name=raw_response,json=rawResponse,proto3" json:"raw_response,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineTransaction) Reset() {
	*x = OnlineTransaction{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineTransaction) ProtoMessage() {}

func (x *OnlineTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineTransaction.ProtoReflect.Descriptor instead.
func (*OnlineTransaction) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *OnlineTransaction) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OnlineTransaction) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *OnlineTransaction) GetProvider() PaymentProvider {
	if x != nil {
		return x.Provider
	}
	return PaymentProvider_PAYMENT_PROVIDER_UNSPECIFIED
}

func (x *OnlineTransaction) GetGatewayRef() string {
	if x != nil {
		return x.GatewayRef
	}
	return ""
}

func (x *OnlineTransaction) GetGatewayStatus() string {
	if x != nil {
		return x.GatewayStatus
	}
	return ""
}

func (x *OnlineTransaction) GetRawResponse() string {
	if x != nil {
		return x.RawResponse
	}
	return ""
}

func (x *OnlineTransaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CODDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentId     int64                  `protobuf:"varint,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	CollectedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CODDetail) Reset() {
	*x = CODDetail{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CODDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CODDetail) ProtoMessage() {}

func (x *CODDetail) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CODDetail.ProtoReflect.Descriptor instead.
func (*CODDetail) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CODDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CODDetail) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *CODDetail) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

func (x *CODDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CODDetail) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Added to authenticate order ownership
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Method        PaymentMethod          `protobuf:"varint,3,opt,name=method,proto3,enum=payment.PaymentMethod" json:"method,omitempty"`
	Provider      PaymentProvider        `protobuf:"varint,4,opt,name=provider,proto3,enum=payment.PaymentProvider" json:"provider,omitempty"`
	GatewayRef    string                 `protobuf:"bytes,5,opt,name=gateway_ref,json=gatewayRef,proto3" json:"gateway_ref,omitempty"`          // Added for PayOnline input
	GatewayStatus string                 `protobuf:"bytes,6,opt,name=gateway_status,json=gatewayStatus,proto3" json:"gateway_status,omitempty"` // Added for PayOnline input
	RawResponse   string                 `protobuf:"bytes,7,opt,name=raw_response,json=rawResponse,proto3" json:"raw_response,omitempty"`       // Added for PayOnline input
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePaymentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePaymentRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreatePaymentRequest) GetMethod() PaymentMethod {
	if x != nil {
		return x.Method
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *CreatePaymentRequest) GetProvider() PaymentProvider {
	if x != nil {
		return x.Provider
	}
	return PaymentProvider_PAYMENT_PROVIDER_UNSPECIFIED
}

func (x *CreatePaymentRequest) GetGatewayRef() string {
	if x != nil {
		return x.GatewayRef
	}
	return ""
}

func (x *CreatePaymentRequest) GetGatewayStatus() string {
	if x != nil {
		return x.GatewayStatus
	}
	return ""
}

func (x *CreatePaymentRequest) GetRawResponse() string {
	if x != nil {
		return x.RawResponse
	}
	return ""
}

type CreatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 🚀 FIXED: Required for validation in GetPaymentByOrderID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{5}
}

func (x *GetPaymentRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *GetPaymentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CollectCODRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // 🚀 FIXED: Required for admin collection action
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectCODRequest) Reset() {
	*x = CollectCODRequest{}
	mi := &file_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectCODRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectCODRequest) ProtoMessage() {}

func (x *CollectCODRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectCODRequest.ProtoReflect.Descriptor instead.
func (*CollectCODRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{6}
}

func (x *CollectCODRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type CollectCODResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectCODResponse) Reset() {
	*x = CollectCODResponse{}
	mi := &file_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectCODResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectCODResponse) ProtoMessage() {}

func (x *CollectCODResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectCODResponse.ProtoReflect.Descriptor instead.
func (*CollectCODResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{7}
}

func (x *CollectCODResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\apayment\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd6\x03\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12.\n" +
	"\x06method\x18\x04 \x01(\x0e2\x16.payment.PaymentMethodR\x06method\x12.\n" +
	"\x06status\x18\x05 \x01(\x0e2\x16.payment.PaymentStatusR\x06status\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12K\n" +
	"\x12online_transaction\x18\t \x01(\v2\x1a.payment.OnlineTransactionH\x00R\x11onlineTransaction\x123\n" +
	"\n" +
	"cod_detail\x18\n" +
	" \x01(\v2\x12.payment.CODDetailH\x00R\tcodDetailB\t\n" +
	"\adetails\"\x9e\x02\n" +
	"\x11OnlineTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\x03R\tpaymentId\x124\n" +
	"\bprovider\x18\x03 \x01(\x0e2\x18.payment.PaymentProviderR\bprovider\x12\x1f\n" +
	"\vgateway_ref\x18\x04 \x01(\tR\n" +
	"gatewayRef\x12%\n" +
	"\x0egateway_status\x18\x05 \x01(\tR\rgatewayStatus\x12!\n" +
	"\fraw_response\x18\x06 \x01(\tR\vrawResponse\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xef\x01\n" +
	"\tCODDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\x03R\tpaymentId\x12=\n" +
	"\fcollected_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9b\x02\n" +
	"\x14CreatePaymentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12.\n" +
	"\x06method\x18\x03 \x01(\x0e2\x16.payment.PaymentMethodR\x06method\x124\n" +
	"\bprovider\x18\x04 \x01(\x0e2\x18.payment.PaymentProviderR\bprovider\x12\x1f\n" +
	"\vgateway_ref\x18\x05 \x01(\tR\n" +
	"gatewayRef\x12%\n" +
	"\x0egateway_status\x18\x06 \x01(\tR\rgatewayStatus\x12!\n" +
	"\fraw_response\x18\a \x01(\tR\vrawResponse\"C\n" +
	"\x15CreatePaymentResponse\x12*\n" +
	"\apayment\x18\x01 \x01(\v2\x10.payment.PaymentR\apayment\"G\n" +
	"\x11GetPaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\".\n" +
	"\x11CollectCODRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\"@\n" +
	"\x12CollectCODResponse\x12*\n" +
	"\apayment\x18\x01 \x01(\v2\x10.payment.PaymentR\apayment*b\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PAYMENT_METHOD_COD\x10\x01\x12\x19\n" +
	"\x15PAYMENT_METHOD_ONLINE\x10\x02*\x8e\x01\n" +
	"\x0fPaymentProvider\x12 \n" +
	"\x1cPAYMENT_PROVIDER_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PAYMENT_PROVIDER_STRIPE\x10\x01\x12\x1f\n" +
	"\x1bPAYMENT_PROVIDER_SSLCOMMERZ\x10\x02\x12\x1b\n" +
	"\x17PAYMENT_PROVIDER_PAYPAL\x10\x03*\xa1\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18PAYMENT_STATUS_COMPLETED\x10\x02\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x03\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\x042\xec\x01\n" +
	"\x0ePaymentService\x12N\n" +
	"\rCreatePayment\x12\x1d.payment.CreatePaymentRequest\x1a\x1e.payment.CreatePaymentResponse\x12C\n" +
	"\x13GetPaymentByOrderId\x12\x1a.payment.GetPaymentRequest\x1a\x10.payment.Payment\x12E\n" +
	"\n" +
	"CollectCOD\x12\x1a.payment.CollectCODRequest\x1a\x1b.payment.CollectCODResponseB>Z<github.com/mafi020/ecom-golang-micro/proto/payment;paymentpbb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_payment_proto_goTypes = []any{
	(PaymentMethod)(0),            // 0: payment.PaymentMethod
	(PaymentProvider)(0),          // 1: payment.PaymentProvider
	(PaymentStatus)(0),            // 2: payment.PaymentStatus
	(*Payment)(nil),               // 3: payment.Payment
	(*OnlineTransaction)(nil),     // 4: payment.OnlineTransaction
	(*CODDetail)(nil),             // 5: payment.CODDetail
	(*CreatePaymentRequest)(nil),  // 6: payment.CreatePaymentRequest
	(*CreatePaymentResponse)(nil), // 7: payment.CreatePaymentResponse
	(*GetPaymentRequest)(nil),     // 8: payment.GetPaymentRequest
	(*CollectCODRequest)(nil),     // 9: payment.CollectCODRequest
	(*CollectCODResponse)(nil),    // 10: payment.CollectCODResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_payment_proto_depIdxs = []int32{
	0,  // 0: payment.Payment.method:type_name -> payment.PaymentMethod
	2,  // 1: payment.Payment.status:type_name -> payment.PaymentStatus
	11, // 2: payment.Payment.created_at:type_name -> google.protobuf.Timestamp
	11, // 3: payment.Payment.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 4: payment.Payment.online_transaction:type_name -> payment.OnlineTransaction
	5,  // 5: payment.Payment.cod_detail:type_name -> payment.CODDetail
	1,  // 6: payment.OnlineTransaction.provider:type_name -> payment.PaymentProvider
	11, // 7: payment.OnlineTransaction.created_at:type_name -> google.protobuf.Timestamp
	11, // 8: payment.CODDetail.collected_at:type_name -> google.protobuf.Timestamp
	11, // 9: payment.CODDetail.created_at:type_name -> google.protobuf.Timestamp
	11, // 10: payment.CODDetail.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 11: payment.CreatePaymentRequest.method:type_name -> payment.PaymentMethod
	1,  // 12: payment.CreatePaymentRequest.provider:type_name -> payment.PaymentProvider
	3,  // 13: payment.CreatePaymentResponse.payment:type_name -> payment.Payment
	3,  // 14: payment.CollectCODResponse.payment:type_name -> payment.Payment
	6,  // 15: payment.PaymentService.CreatePayment:input_type -> payment.CreatePaymentRequest
	8,  // 16: payment.PaymentService.GetPaymentByOrderId:input_type -> payment.GetPaymentRequest
	9,  // 17: payment.PaymentService.CollectCOD:input_type -> payment.CollectCODRequest
	7,  // 18: payment.PaymentService.CreatePayment:output_type -> payment.CreatePaymentResponse
	3,  // 19: payment.PaymentService.GetPaymentByOrderId:output_type -> payment.Payment
	10, // 20: payment.PaymentService.CollectCOD:output_type -> payment.CollectCODResponse
	18, // [18:21] is the sub-list for method output_type
	15, // [15:18] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	file_payment_proto_msgTypes[0].OneofWrappers = []any{
		(*Payment_OnlineTransaction)(nil),
		(*Payment_CodDetail)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		EnumInfos:         file_payment_proto_enumTypes,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
